# Generated by Django 5.2 on 2025-04-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_size', models.PositiveIntegerField(default=200)),
                ('qr_code_color', models.CharField(default='#000000', max_length=7)),
                ('qr_code_background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('qr_code_module_drawer', models.CharField(choices=[('rounded', 'Rounded'), ('circle', 'Circle')], default='rounded', max_length=20)),
                ('qr_code_color_mask', models.CharField(choices=[('radial', 'Radial'), ('linear', 'Linear')], default='radial', max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='menu.menutemplate')),
            ],
        ),
    ]
